image: .gitpod.Dockerfile

tasks:
  - init: 'echo "Iniciando"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.5:P2IAAqkG33Qk7a8Z/Ip6eg==
    - Angular.ng-template@0.1100.0:7oR3tO6ugyY+mWGZtMigtg==