version: "3"

services:
  api:
    build: ./ApiAlunos
    container_name: alunofront
    networks:
      - aluno_network
      - proxy
    labels: 
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.alunofront.entrypoint=http"
      - "traefik.http.routers.alunofront.rule=Host(`desafioaevo.dodev.dev`) && (PathPrefix(`/api`)"
      - "traefik.http.midlewares.alunofront-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.alunofront-secure.entrypoints=https"
      - "traefik.http.routers.alunofront-secure.rule=Host(`desafioaevo.dodev.dev`)"
      - "traefik.http.routers.alunofront-secure.tls=true"
      - "traefik.http.routers.alunofront-secure.tls.certresolver=http"
      - "traefik.http.routers.alunofront-secure.service=alunofront"
      - "traefik.http.services.alunofront.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    depends_on:
      - db

  db:
    build: ./Database
    container_name: alunodb
    user: root
    networks:
      - aluno_network
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=C0ns7tasDbp23
    volumes:
      - aluno_data:/var/opt/mssql/

  front:
    build: ./FrontAlunos
    container_name: alunofront
    networks: 
      - aluno_network
      - proxy
    labels: 
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.alunofront.entrypoint=http"
      - "traefik.http.routers.alunofront.rule=Host(`desafioaevo.dodev.dev`)"
      - "traefik.http.midlewares.alunofront-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.alunofront-secure.entrypoints=https"
      - "traefik.http.routers.alunofront-secure.rule=Host(`desafioaevo.dodev.dev`)"
      - "traefik.http.routers.alunofront-secure.tls=true"
      - "traefik.http.routers.alunofront-secure.tls.certresolver=http"
      - "traefik.http.routers.alunofront-secure.service=alunofront"
      - "traefik.http.services.alunofront.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    
    

volumes:
  aluno_data:

networks:
  aluno_network:
  proxy:
    external: 
      name: proxy
