version: "3"

services:
  api:
    build: ./ApiAlunos
    container_name: alunoapi
    networks:
      - aluno_network
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    build: ./Database
    container_name: alunoapi_db
    user: root
    networks:
      - aluno_network
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=C0ns7tasDbp23
    volumes:
      - aluno_data:/var/opt/mssql/

volumes:
  aluno_data:

networks:
  aluno_network:
